# Generated by Django 3.1.6 on 2021-10-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_buyorders_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyorders',
            name='BuyAmount',
        ),
        migrations.RemoveField(
            model_name='buyorders',
            name='PaymentMethod',
        ),
    ]
