# Generated by Django 3.1.6 on 2021-10-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211027_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorders',
            name='paymentpethod',
            field=models.CharField(default='', max_length=50),
        ),
    ]
